# encoding:utf-8

COURSE_PROGRESS_STATUS_TEMPLATE_NAME = "progress 1"
COURSE_PROGRESS_STATUS_MAIL_TITLE = "Teachcast 学习进度"
#COURSE_PROGRESS_STATUS_MAIL_FROM = "eleutiancs@163.com"
COURSE_PROGRESS_STATUS_MAIL_FROM ="marketchina@eleutian.com"